image: node:latest
stages:
  - install
  - test
install:
  stage: install
  script: npm install
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
test:
  stage: test
  dependencies:
    - install
  script: npm test